import image1 from "../../assets/img/wallet/1.png"
import image2 from "../../assets/img/wallet/2.png"
import image3 from "../../assets/img/wallet/3.png"
import image4 from "../../assets/img/wallet/4.png"
import image5 from "../../assets/img/wallet/5.jpg"
import image6 from "../../assets/img/wallet/6.jpg"
import image7 from "../../assets/img/wallet/7.jpg"
import image8 from "../../assets/img/wallet/8.jpg"
import image9 from "../../assets/img/wallet/9.jpg"
import image10 from "../../assets/img/wallet/10.jpg"
import image11 from "../../assets/img/wallet/11.jpg"
import image12 from "../../assets/img/wallet/12.jpg"
import image13 from "../../assets/img/wallet/13.jpg"
import image14 from "../../assets/img/wallet/14.jpg"
import image15 from "../../assets/img/wallet/15.jpg"
import image16 from "../../assets/img/wallet/16.jpg"
import image17 from "../../assets/img/wallet/17.jpg"
import image18 from "../../assets/img/wallet/18.jpg"
import image19 from "../../assets/img/wallet/19.jpg"
import image20 from "../../assets/img/wallet/20.jpg"
import image21 from "../../assets/img/wallet/21.jpg"


export default [image1,image2,image3,image4,image5,image6,image7,image8,image9,image10,image11,image12,image13,image14,image15,image16,image17,image18,image19,image20,image21];